export const studyLogs = [
  {
    title: 'Ep.073',
    category: '聴く',
    date: new Date(11 / 9 / 2023),
    time: 29,
    resourceId: 1,
    userId: 2500,
  },
  {
    title: '[Japanese conversation] Talk to the staff at a cafe. Chiba Vlog',
    category: '聴く',
    date: new Date(11 / 10 / 2023),
    time: 13,
    resourceId: 2,
    userId: 2500,
  },
  {
    title: '第０話, read 10 pages',
    category: '読書',
    date: new Date(11 / 6 / 2023),
    time: 10,
    resourceId: 3,
    userId: 2500,
  },
  {
    title: 'Episode 40',
    category: '観る',
    date: new Date(11 / 9 / 2023),
    time: 20,
    resourceId: 4,
    userId: 2500,
  },
  {
    title: 'Lesson with Aoi',
    category: '話す',
    date: new Date(11 / 9 / 2023),
    time: 30,
    resourceId: 5,
    userId: 2500,
  },
];

export const resources = [
  {
    id: 1,
    name: 'Not Straight! 〜クィアな2人の井戸端会議〜',
    type: 'Podcast',
    status: 'Current',
    link: '',
    notes: 'Queer content for the win!',
    userId: 2500,
  },
  {
    id: 2,
    name: 'あかね的日本語教室',
    type: 'YouTube Channel',
    status: 'Current',
    link: 'https://www.youtube.com/@Akane-JapaneseClass',
    notes: 'Excellent listening practice.',
    userId: 2500,
  },
  {
    id: 3,
    name: '僕らの食卓',
    type: 'Manga',
    status: 'Current',
    link: 'https://myanimelist.net/manga/104491/Bokura_no_Shokutaku',
    notes: 'No furigana.',
    userId: 2500,
  },
  {
    id: 4,
    name: '呪術廻戦 2',
    type: 'Anime',
    status: 'Current',
    link: 'https://myanimelist.net/anime/51009/Jujutsu_Kaisen_2nd_Season',
    notes: 'Difficult language, but great show.',
    userId: 2500,
  },
  {
    id: 5,
    name: 'iTalki',
    type: 'Website',
    status: 'Current',
    link: 'https://www.italki.com/',
    notes: 'Great website for speaking practice.',
    userId: 2500,
  },
];
